name: 'Docker Publish'
description: 'Publish Docker images to GitHub Container Registry and Docker Hub'

inputs:
  image:
    description: 'Docker image name'
    required: true
  tags:
    description: 'Docker image tag'
    required: true
  registry:
    description: 'Docker registry URL'
    required: true
  registry_username:
    description: 'Username for the Docker registry'
    required: true
  registry_password:
      description: 'Password for the Docker registry'
      required: true

runs:
  using: 'composite'
  steps:
    - name: Login to Registry
      shell: bash
      run: |
        echo "${{ inputs.registry_password }}" | docker login ${{ inputs.registry }} -u ${{ inputs.registry_username }} --password-stdin

    - name: Publish Image
      shell: bash
      run: |
        for tag in $(echo "${{ inputs.tags }}" | xargs); do
          echo "Tagging image with: $tag"
          docker tag "${{ inputs.image }}" "$tag"

          echo "Pushing image: $tag"
          docker push "$tag"
        done